DELETE FROM PROJECT_TO_TAG WHERE PROJECT_TO_TAG_FK NOT IN (
     SELECT MIN(PROJECT_TO_TAG_FK) FROM PROJECT_TO_TAG GROUP BY PROJECT_FK, TAG_FK);
CREATE UNIQUE INDEX idx_project_to_tag_unique ON PROJECT_TO_TAG (PROJECT_FK, TAG_FK);
