CREATE TABLE IF NOT EXISTS VERSION_CHECK (
    SOURCE_FK       INTEGER PRIMARY KEY,
    LAST_CHECKED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now')),
    NEW_VERSION     INTEGER,
    FOREIGN KEY (SOURCE_FK) REFERENCES PAPER_ROOTS(SOURCE_FK) ON DELETE CASCADE
);
