BEGIN;
 CREATE TABLE PAPER_TO_READING_NEW(
     PROJECT_FK  INTEGER NOT NULL,
     SOURCE_FK   INTEGER NOT NULL,
     STATUS      TEXT    NOT NULL CHECK (STATUS IN ('reading', 'read')),
     UPDATED_AT  TIMESTAMP NOT NULL DEFAULT (datetime('now')),
     PRIMARY KEY (PROJECT_FK, SOURCE_FK),
     FOREIGN KEY (PROJECT_FK, SOURCE_FK) REFERENCES PROJECT_TO_PAPER(PROJECT_FK, SOURCE_FK) ON DELETE CASCADE
 );
 INSERT INTO PAPER_TO_READING_NEW (PROJECT_FK, SOURCE_FK, STATUS, UPDATED_AT)
     SELECT r.PROJECT_FK, r.SOURCE_FK, r.STATUS, r.UPDATED_AT
     FROM PAPER_TO_READING r
     JOIN PROJECT_TO_PAPER m ON m.PROJECT_FK = r.PROJECT_FK AND m.SOURCE_FK = r.SOURCE_FK;
 DROP TABLE PAPER_TO_READING;
 ALTER TABLE PAPER_TO_READING_NEW RENAME TO PAPER_TO_READING;
 CREATE INDEX IF NOT EXISTS idx_paper_to_reading_source_fk ON PAPER_TO_READING (SOURCE_FK);
 COMMIT;
