//! TypeScript bindings for the wire types (test-only).
//!
//! `src/types/generated.ts` is a **checked-in artifact** — the frontend builds
//! from a clean clone with no cargo step. This module is the generator and the
//! drift check in one: [`tests::bindings_are_current`] renders every
//! `#[derive(TS)]` serializer and asserts the checked-in file matches.
//!
//! Regenerate: `npm run types:gen` (`UPDATE_BINDINGS=1 cargo test -p
//! linxiv-server ts_bindings`). Verify: `npm run types:check`.
//!
//! Lives in linxiv-server (moved from linxiv-core) because this crate tops the
//! dependency graph: one `render()` reaches core's models/services, the share
//! crate, AND this crate's own route request structs. The app crate above us
//! keeps its one hand-synced type (`RemoteBackend` in src/api/client.ts) —
//! rendering it would drag the Tauri build into `types:gen`.
//!
//! Only types with ONE canonical serializer belong here (CONTEXT.md
//! § Serializer Convention). The wire shapes still assembled by inline `json!`
//! in a route handler have no struct to generate from and stay hand-written in
//! `src/types/api.ts`, each with a comment saying why.

use ts_rs::{Config, TS};

/// `i64` → `number`, not ts-rs's default `bigint`: the wire is JSON and
/// `JSON.parse` already hands the frontend a `number` for every id. (SQLite
/// rowids in a desktop library never approach 2^53.)
fn cfg() -> Config {
    Config::new().with_large_int("number")
}

const HEADER: &str = "\
// Generated by `npm run types:gen` from the #[derive(TS)] wire types across
// the workspace. DO NOT EDIT — `npm run types:check` fails when this file drifts
// from the Rust source. Frontend-facing aliases and the shapes that have no
// single Rust struct live in ./api.ts.
";

/// `export type X = ...;` for one `TS` type, blank-line separated.
fn decl<T: TS + ?Sized>() -> String {
    format!("\nexport {}\n", pretty(T::decl(&cfg())))
}

/// ts-rs emits a declaration on one line. Break the object body to one member
/// per line so a drifted field is a one-line diff instead of a rewritten
/// paragraph. Splits on top-level commas only, so `Array<A, B>` stays intact;
/// anything that isn't a `{ … }` body (a union like `Status`) passes through.
/// ts-rs's `format` feature would do this too, at the cost of 45 crates.
///
/// A comma inside a JSDoc block is prose, not a member separator: ts-rs carries
/// the Rust doc comment through verbatim, so splitting on those commas chopped
/// a doc sentence across lines mid-clause and indented each fragment as its own
/// member. Track the `/* … */` span and only split outside it.
fn pretty(decl: String) -> String {
    let (Some(open), Some(close)) = (decl.find("{ "), decl.rfind(" }")) else {
        return decl;
    };
    /// Append one member, indented, keeping a JSDoc block's `*` column.
    fn flush(member: &str, out: &mut String) {
        for line in member.trim().lines() {
            let line = line.trim_start();
            out.push_str(if line.starts_with('*') { "   " } else { "  " });
            out.push_str(line);
            out.push('\n');
        }
    }

    let mut out = format!("{}{{\n", &decl[..open]);
    let mut depth = 0i32;
    let mut in_comment = false;
    let mut prev = '\0';
    let mut member = String::new();
    for c in decl[open + 1..close].chars() {
        if in_comment {
            // Closing `*/` — `prev` is the `*`, so the slash ends the block.
            if prev == '*' && c == '/' {
                in_comment = false;
            }
            member.push(c);
            prev = c;
            continue;
        }
        if prev == '/' && c == '*' {
            in_comment = true;
            member.push(c);
            prev = c;
            continue;
        }
        match c {
            '<' | '{' | '[' | '(' => depth += 1,
            '>' | '}' | ']' | ')' => depth -= 1,
            ',' if depth == 0 => {
                member.push(',');
                flush(&member, &mut out);
                member.clear();
                prev = '\0';
                continue;
            }
            _ => {}
        }
        member.push(c);
        prev = c;
    }
    flush(&member, &mut out);
    out.push('}');
    out.push_str(&decl[close + 2..]);
    out
}

/// The full contents of `src/types/generated.ts`.
pub(crate) fn render() -> String {
    use linxiv_core::models::*;
    let mut out = String::from(HEADER);
    out.push_str(&decl::<PaperDetails>());
    out.push_str(&decl::<SearchResultOut>());
    out.push_str(&decl::<ArxivSearchResponse>());
    out.push_str(&decl::<ArxivFetchResponse>());
    out.push_str(&decl::<OpenAlexSearchResponse>());
    out.push_str(&decl::<Status>());
    out.push_str(&decl::<ProjectOut>());
    out.push_str(&decl::<NoteDetails>());
    out.push_str(&decl::<AnnotationDetails>());
    out.push_str(&decl::<BasicAuthorDetails>());
    out.push_str(&decl::<AuthorWithCount>());
    out.push_str(&decl::<AuthorPaperPreview>());
    out.push_str(&decl::<AuthorWithPapers>());
    out.push_str(&decl::<linxiv_core::service::stats::Stats>());
    out.push_str(&decl::<
        linxiv_core::storage::queries::paper::DoiVersionCandidate,
    >());
    out.push_str(&decl::<linxiv_core::service::paper::FullTextReceipt>());
    out.push_str(&decl::<linxiv_core::service::project::PaperMembershipReceipt>());
    out.push_str(&decl::<
        linxiv_core::service::paper_import::BibtexImportReceipt,
    >());
    out.push_str(&decl::<linxiv_core::service::paper_merge::MergeReceipt>());
    out.push_str(&decl::<linxiv_core::storage::queries::rss::FilterField>());
    out.push_str(&decl::<linxiv_core::storage::queries::rss::FilterAction>());
    out.push_str(&decl::<linxiv_core::storage::queries::rss::FilterRule>());
    out.push_str(&decl::<linxiv_core::graph::GraphPaper>());
    out.push_str(&decl::<linxiv_core::graph::GraphAuthor>());
    out.push_str(&decl::<linxiv_core::graph::GraphTag>());
    out.push_str(&decl::<linxiv_core::graph::GraphEdge>());
    out.push_str(&decl::<linxiv_core::graph::GraphProject>());
    out.push_str(&decl::<linxiv_core::graph::GraphView>());
    out.push_str(&decl::<TagWithCount>());
    out.push_str(&decl::<
        linxiv_core::storage::queries::version_check::NewVersion,
    >());
    out.push_str(&decl::<linxiv_core::storage::queries::author::OrcidCandidate>());
    out.push_str(&decl::<linxiv_core::service::export_import::ImportPreview>());
    out.push_str(&decl::<linxiv_core::storage::backup::BackupInfo>());
    out.push_str(&decl::<linxiv_core::service::paper::DeletedPaperDetails>());
    out.push_str(&decl::<linxiv_core::service::trash::TrashedProjectRow>());
    out.push_str(&decl::<linxiv_core::service::trash::RestoredPaper>());
    out.push_str(&decl::<
        linxiv_core::service::editor_project::EditorProjectSummary,
    >());
    out.push_str(&decl::<linxiv_core::service::files::SavedPdf>());
    out.push_str(&decl::<linxiv_core::service::author::MergeCandidates>());
    // papers / uploads / pdfs route group
    out.push_str(&decl::<linxiv_core::service::paper::PapersListing>());
    out.push_str(&decl::<
        linxiv_core::storage::queries::paper::PaperVersionMeta,
    >());
    out.push_str(&decl::<linxiv_core::service::paper::PaperVersionsResponse>());
    out.push_str(&decl::<linxiv_core::service::paper::DoiCandidates>());
    out.push_str(&decl::<linxiv_core::service::paper::FullTextPending>());
    out.push_str(&decl::<linxiv_core::service::paper::SavedSourceIds>());
    out.push_str(&decl::<linxiv_core::service::paper::DeletedPaperReceipt>());
    out.push_str(&decl::<linxiv_core::service::project::RemovedFromProjects>());
    out.push_str(&decl::<OkReceipt>());
    out.push_str(&decl::<linxiv_core::service::paper_import::PaperImportResult>());
    out.push_str(&decl::<
        linxiv_core::service::export_import::ImportPreviewResponse,
    >());
    out.push_str(&decl::<linxiv_core::service::export_import::ImportedProject>());
    out.push_str(&decl::<linxiv_core::service::files::SavedPdfListing>());
    out.push_str(&decl::<linxiv_core::service::files::DeletedPdf>());
    // Library-organization route group (route/{projects,tags,authors}.rs).
    out.push_str(&decl::<ProjectsResponse>());
    out.push_str(&decl::<CreatedProject>());
    out.push_str(&decl::<linxiv_core::service::project::BulkAddReceipt>());
    out.push_str(&decl::<linxiv_core::service::tag::TagsResponse>());
    out.push_str(&decl::<linxiv_core::service::tag::TagDetail>());
    out.push_str(&decl::<AuthorsResponse>());
    out.push_str(&decl::<AuthorMergeResponse>());
    // sources/notes/reading-status/annotations route envelopes
    out.push_str(&decl::<PaperMetadata>());
    out.push_str(&decl::<OpenAlexSaveResponse>());
    out.push_str(&decl::<DoiResolveResponse>());
    out.push_str(&decl::<DoiSaveResponse>());
    out.push_str(&decl::<linxiv_core::service::note::NoteListResponse>());
    out.push_str(&decl::<linxiv_core::service::note::NoteGetResponse>());
    out.push_str(&decl::<linxiv_core::service::note::DeletedNote>());
    out.push_str(&decl::<
        linxiv_core::service::annotation::AnnotationListResponse,
    >());
    out.push_str(&decl::<linxiv_core::service::annotation::CreatedAnnotation>());
    out.push_str(&decl::<
        linxiv_core::service::reading_list::ReadingStatusesResponse,
    >());
    out.push_str(&decl::<
        linxiv_core::service::reading_list::ReadingStatusReceipt,
    >());
    // small-route envelopes: editor / search / versions / feed / orcid / trash
    out.push_str(&decl::<
        linxiv_core::service::editor_project::EditorProjectsResponse,
    >());
    out.push_str(&decl::<
        linxiv_core::service::search_state::SearchHistoryResponse,
    >());
    out.push_str(&decl::<
        linxiv_core::service::version_monitor::VersionCheckResponse,
    >());
    out.push_str(&decl::<
        linxiv_core::service::version_monitor::NewVersionsResponse,
    >());
    out.push_str(&decl::<linxiv_core::service::feed::FeedRulesResponse>());
    out.push_str(&decl::<linxiv_core::service::feed::CreatedFeedRule>());
    out.push_str(&decl::<
        linxiv_core::service::orcid_backfill::OrcidBackfillResponse,
    >());
    out.push_str(&decl::<linxiv_core::service::trash::HardDeletedPaper>());
    out.push_str(&decl::<linxiv_core::service::trash::RestoredProject>());
    out.push_str(&decl::<linxiv_core::service::trash::HardDeletedProject>());
    // Request bodies — the shapes the frontend SENDS, from the route files'
    // `parse_body` structs. Share's bodies stay hand-parsed (bespoke per-field
    // 422 contract); SearchStateBody and the free-form settings patch carry
    // untyped JSON and stay hand-written in src/types/api.ts.
    out.push_str(&decl::<crate::route::papers::PaperSavedBody>());
    out.push_str(&decl::<crate::route::papers::PaperMergeBody>());
    out.push_str(&decl::<linxiv_core::service::paper::RepairFields>());
    out.push_str(&decl::<crate::route::versions::VersionsCheckBody>());
    out.push_str(&decl::<crate::route::versions::VersionsAckBody>());
    out.push_str(&decl::<crate::route::uploads::UploadPdfBody>());
    out.push_str(&decl::<crate::route::uploads::ImportPdfBody>());
    out.push_str(&decl::<crate::route::uploads::ImportBibtexBody>());
    out.push_str(&decl::<crate::route::uploads::ImportPreviewBody>());
    out.push_str(&decl::<crate::route::uploads::ImportCommitBody>());
    out.push_str(&decl::<crate::route::orcid::OrcidBackfillBody>());
    out.push_str(&decl::<crate::route::tags::TagCreateBody>());
    out.push_str(&decl::<crate::route::tags::PaperTagsBody>());
    out.push_str(&decl::<crate::route::storage::StorageBackupBody>());
    out.push_str(&decl::<crate::route::storage::StorageRestoreBody>());
    out.push_str(&decl::<crate::route::sources::ArxivSearchBody>());
    out.push_str(&decl::<crate::route::sources::ArxivFetchBody>());
    out.push_str(&decl::<crate::route::sources::OpenAlexSearchBody>());
    out.push_str(&decl::<crate::route::sources::OpenAlexSaveBody>());
    out.push_str(&decl::<crate::route::sources::CrossrefSearchBody>());
    out.push_str(&decl::<crate::route::sources::DoiResolveBody>());
    out.push_str(&decl::<crate::route::sources::DoiSaveBody>());
    out.push_str(&decl::<crate::route::feed::FeedDismissBody>());
    out.push_str(&decl::<crate::route::feed::FeedRuleCreateBody>());
    out.push_str(&decl::<crate::route::editor::CreateEditorProjectBody>());
    out.push_str(&decl::<crate::route::settings::EnvPatchBody>());
    out.push_str(&decl::<crate::route::notes::NoteCreateBody>());
    out.push_str(&decl::<crate::route::notes::NoteUpdateBody>());
    out.push_str(&decl::<crate::route::authors::AuthorUpdateBody>());
    out.push_str(&decl::<crate::route::authors::AuthorMergeBody>());
    out.push_str(&decl::<crate::route::annotations::AnnotationCreateBody>());
    out.push_str(&decl::<crate::route::annotations::AnnotationUpdateBody>());
    out.push_str(&decl::<crate::route::reading_status::ReadingStatusPutBody>());
    out.push_str(&decl::<crate::route::projects::ProjectCreateBody>());
    out.push_str(&decl::<crate::route::projects::ProjectUpdateBody>());
    out.push_str(&decl::<crate::route::projects::ProjectAddPaperBody>());
    out.push_str(&decl::<crate::route::projects::ProjectAddPapersBulkBody>());
    out.push_str(&decl::<crate::route::projects::ProjectExportBody>());
    out
}

#[cfg(test)]
mod tests {
    use super::render;

    /// Repo-root-relative: this crate is `<repo>/src-tauri/crates/core`.
    const BINDINGS: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../src/types/generated.ts"
    );

    #[test]
    fn bindings_are_current() {
        let want = render();
        if std::env::var_os("UPDATE_BINDINGS").is_some() {
            std::fs::write(BINDINGS, &want).expect("write generated.ts");
            return;
        }
        let have = std::fs::read_to_string(BINDINGS).unwrap_or_default();
        if have == want {
            return;
        }
        // Report the first differing line, not two full files: `assert_eq!` on
        // 150 lines of TypeScript prints an escaped blob nobody can read.
        let (n, checked_in, generated) = have
            .lines()
            .map(Some)
            .chain(std::iter::repeat(None))
            .zip(want.lines().map(Some).chain(std::iter::repeat(None)))
            .enumerate()
            .find(|(_, (a, b))| a != b)
            .map(|(i, (a, b))| (i + 1, a.unwrap_or("<eof>"), b.unwrap_or("<eof>")))
            .expect("contents differ, so some line differs");
        panic!(
            "src/types/generated.ts is stale — run `npm run types:gen`\n\
             line {n}:\n  checked in: {checked_in}\n  generated:  {generated}"
        );
    }
}
