//! pdf_metadata — Rust port of `sources/pdf_metadata.py` (D10 spike).
//!
//! Parser over PDF bytes: pdfium (native libpdfium) for first-page text and the
//! Info dict (/Title /Author /CreationDate) — ~22x faster than lopdf on large PDFs
//! with cleaner text (proper newlines). The arXiv-id and
//! DOI scanners, the 3-line title heuristic, and the autogenerated-title /
//! junk-author filters are hand-rolled (no `regex` dep in this crate). Extraction
//! is catch-and-fall-through: a malformed PDF degrades to an all-None record. The
//! catch covers a pdfium *panic* under an unwind profile only — see the D30 note in
//! `extract_pdf_metadata` for the release/`abort` and native-segfault caveats.
//!
//! `resolve_pdf_metadata` builds the local-identity `PaperMetadata`, enriching
//! it from an upstream record (arXiv/DOI/CrossRef, see `enrich_external`) when an
//! id matches, else falling back to the Python "all resolution fails" partial.

use std::path::Path;
use std::sync::OnceLock;

use chrono::{Datelike, NaiveDate, Utc};
use pdfium_render::prelude::*;

use crate::error::Result;
use crate::models::PaperMetadata;
use crate::sources::{arxiv, crossref, doi_resolve};

// ---------------------------------------------------------------------------
// Raw extraction result (mirrors the Python dict; `abstract` is always None).
// ---------------------------------------------------------------------------

#[derive(Debug, Default, Clone, PartialEq)]
pub(crate) struct Extracted {
    pub title: Option<String>,
    pub authors: Option<String>,
    pub doi: Option<String>,
    pub arxiv_id: Option<String>,
    pub year: Option<i32>,
}

// ---------------------------------------------------------------------------
// Small char-class helpers (\w == [A-Za-z0-9_])
// ---------------------------------------------------------------------------

fn is_word(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

// ---------------------------------------------------------------------------
// arXiv id:  arXiv:(\d{4}\.\d{4,5}(?:v\d+)?)   (case-insensitive)
// ---------------------------------------------------------------------------

/// Length (bytes) of an arXiv id at the start of `b`, or None.
fn match_arxiv(b: &[u8]) -> Option<usize> {
    if b.len() < 5 || !b[..4].iter().all(u8::is_ascii_digit) || b[4] != b'.' {
        return None;
    }
    let ds = 5;
    let mut j = ds;
    while j < b.len() && b[j].is_ascii_digit() && j - ds < 5 {
        j += 1;
    }
    if j - ds < 4 {
        return None; // \d{4,5}
    }
    if j < b.len() && (b[j] == b'v' || b[j] == b'V') {
        let mut m = j + 1;
        while m < b.len() && b[m].is_ascii_digit() {
            m += 1;
        }
        if m > j + 1 {
            j = m; // only consume `v` if followed by \d+
        }
    }
    Some(j)
}

pub(crate) fn extract_arxiv_id(text: &str) -> Option<String> {
    let lower = text.to_ascii_lowercase();
    let lb = lower.as_bytes();
    let tb = text.as_bytes();
    let mut i = 0;
    while i + 6 <= lb.len() {
        if &lb[i..i + 6] == b"arxiv:" {
            let s = i + 6;
            if let Some(len) = match_arxiv(&tb[s..]) {
                return Some(text[s..s + len].to_string());
            }
        }
        i += 1;
    }
    None
}

// ---------------------------------------------------------------------------
// DOI:  \b10\.\d{4,}/\S+   then rstrip ".,)"
// ---------------------------------------------------------------------------

pub(crate) fn extract_doi(text: &str) -> Option<String> {
    let b = text.as_bytes();
    let n = b.len();
    let mut i = 0;
    while i + 3 <= n {
        if b[i] == b'1' && b[i + 1] == b'0' && b[i + 2] == b'.' {
            let boundary = i == 0 || !is_word(b[i - 1]); // \b
            if boundary {
                let ds = i + 3;
                let mut j = ds;
                while j < n && b[j].is_ascii_digit() {
                    j += 1;
                }
                if j - ds >= 4 && j < n && b[j] == b'/' {
                    let mut k = j + 1;
                    while k < n && !b[k].is_ascii_whitespace() {
                        k += 1;
                    }
                    if k > j + 1 {
                        let raw = &text[i..k];
                        let cleaned = raw.trim_end_matches(['.', ',', ')']);
                        return Some(cleaned.to_string());
                    }
                }
            }
        }
        i += 1;
    }
    None
}

// ---------------------------------------------------------------------------
// Title heuristic + junk filters
// ---------------------------------------------------------------------------

pub(crate) fn looks_autogenerated(title: &str) -> bool {
    if title.trim().is_empty() {
        return true; // ^\s*$
    }
    let lt = title.to_ascii_lowercase();
    lt.starts_with("microsoft word") || lt.starts_with("untitled") || lt.starts_with("powerpoint")
}

/// `\bWindows\b` anywhere, or the whole string == User/Admin/Benutzer/Utilisateur.
pub(crate) fn looks_junk_author(author: &str) -> bool {
    let la = author.to_ascii_lowercase();
    let t = la.trim();
    if matches!(t, "user" | "admin" | "benutzer" | "utilisateur") {
        return true;
    }
    contains_word(&la, b"windows")
}

fn contains_word(hay: &str, needle: &[u8]) -> bool {
    let hb = hay.as_bytes();
    let mut i = 0;
    while i + needle.len() <= hb.len() {
        if &hb[i..i + needle.len()] == needle {
            let before = i == 0 || !is_word(hb[i - 1]);
            let after = i + needle.len() == hb.len() || !is_word(hb[i + needle.len()]);
            if before && after {
                return true;
            }
        }
        i += 1;
    }
    false
}

/// `\b[A-Z][a-z]+,\s*\d` — a surname-then-affiliation-superscript line.
fn is_author_line(s: &str) -> bool {
    let b = s.as_bytes();
    let n = b.len();
    for i in 0..n {
        if !b[i].is_ascii_uppercase() || (i > 0 && is_word(b[i - 1])) {
            continue;
        }
        let mut j = i + 1;
        while j < n && b[j].is_ascii_lowercase() {
            j += 1;
        }
        if j == i + 1 || j >= n || b[j] != b',' {
            continue; // need [a-z]+ then ','
        }
        let mut k = j + 1;
        while k < n && (b[k] == b' ' || b[k] == b'\t') {
            k += 1; // \s*
        }
        if k < n && b[k].is_ascii_digit() {
            return true;
        }
    }
    false
}

pub(crate) fn extract_title_from_text(text: &str) -> Option<String> {
    let mut lines: Vec<&str> = Vec::new();
    for raw in text.lines() {
        let s = raw.trim();
        if s.is_empty() {
            if !lines.is_empty() {
                break; // blank line after content — title block ended
            }
            continue; // leading blank
        }
        if is_author_line(s) {
            break;
        }
        lines.push(s);
        if lines.len() == 3 {
            break;
        }
    }
    if lines.is_empty() {
        None
    } else {
        Some(lines.join(" "))
    }
}

// ---------------------------------------------------------------------------
// Jaccard title similarity (used by deferred CrossRef enrichment).
// ---------------------------------------------------------------------------

#[allow(dead_code)] // consumed by the deferred CrossRef enrichment (enrich_external)
fn words(s: &str) -> std::collections::HashSet<String> {
    let mut set = std::collections::HashSet::new();
    let mut cur = String::new();
    for c in s.chars() {
        if c.is_alphanumeric() || c == '_' {
            cur.extend(c.to_lowercase());
        } else if !cur.is_empty() {
            set.insert(std::mem::take(&mut cur));
        }
    }
    if !cur.is_empty() {
        set.insert(cur);
    }
    set
}

#[allow(dead_code)] // consumed by the deferred CrossRef enrichment (enrich_external)
pub(crate) fn title_similarity(a: &str, b: &str) -> f64 {
    let wa = words(a);
    let wb = words(b);
    if wa.is_empty() || wb.is_empty() {
        return 0.0;
    }
    wa.intersection(&wb).count() as f64 / wa.union(&wb).count() as f64
}

// ---------------------------------------------------------------------------
// Year from a PDF date string (first 4-digit run, validated 1900..=now+1).
// ---------------------------------------------------------------------------

fn parse_year(date_str: &str) -> Option<i32> {
    let b = date_str.as_bytes();
    let mut i = 0;
    while i + 4 <= b.len() {
        if b[i..i + 4].iter().all(u8::is_ascii_digit) {
            let y: i32 = std::str::from_utf8(&b[i..i + 4]).ok()?.parse().ok()?;
            // Python does a single re.search then validates; out-of-range -> None.
            return (1900..=Utc::now().year() + 1).contains(&y).then_some(y);
        }
        i += 1;
    }
    None
}

// ---------------------------------------------------------------------------
// pdfium binding + Info dict + first-page text
// ---------------------------------------------------------------------------

/// Resolve the libpdfium path ONCE (cheap; reused for each per-call bind). Order:
/// `LINXIV_PDFIUM_LIB` env → a `pdfium/` dir next to the executable (the bundled
/// location) → (debug builds only) the dev vendor dir (`scripts/fetch_pdfium.sh`).
/// `None` → fall back to the system library at bind time. The build-host vendor
/// path is `cfg(debug_assertions)`-gated so it can't be baked into a shipped binary.
fn pdfium_lib_path() -> Option<&'static std::path::Path> {
    static LIB: OnceLock<Option<std::path::PathBuf>> = OnceLock::new();
    LIB.get_or_init(|| {
        let in_dir = |dir: std::path::PathBuf| {
            let p = Pdfium::pdfium_platform_library_name_at_path(&dir);
            p.exists().then_some(p)
        };
        if let Some(p) = std::env::var_os("LINXIV_PDFIUM_LIB") {
            return Some(std::path::PathBuf::from(p));
        }
        if let Some(p) = std::env::current_exe()
            .ok()
            .and_then(|e| e.parent().map(|d| d.join("pdfium")))
            .and_then(in_dir)
        {
            return Some(p);
        }
        #[cfg(debug_assertions)]
        if let Some(p) = in_dir(std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../vendor/pdfium/lib"
        ))) {
            return Some(p);
        }
        None
    })
    .as_deref()
}

/// Bind libpdfium for a SINGLE extraction; the caller drops it immediately after.
/// Mechanism: `thread_safe` takes a process-global lock inside `FPDF_InitLibrary`
/// (`Pdfium::new`) and releases it in `FPDF_DestroyLibrary` (`Drop`), i.e. it is
/// held for the instance's whole lifetime. So a per-call instance frees the lock
/// each call and concurrent extractions queue on it; a long-lived/per-thread
/// instance would pin the lock and the next caller's `new` would block forever.
fn bind_pdfium() -> Option<Pdfium> {
    let bindings = match pdfium_lib_path() {
        Some(p) => Pdfium::bind_to_library(p).ok(),
        None => Pdfium::bind_to_system_library().ok(),
    };
    match bindings {
        Some(b) => Some(Pdfium::new(b)),
        None => {
            static WARNED: std::sync::Once = std::sync::Once::new();
            WARNED.call_once(|| {
                tracing::error!(
                    "libpdfium not found — PDF metadata extraction disabled; run \
                     scripts/fetch_pdfium.sh or set LINXIV_PDFIUM_LIB"
                )
            });
            None
        }
    }
}

/// Non-empty Info-dict value for `tag`, else None (mirrors `meta.get(k) or None`).
fn meta_get(md: &PdfMetadata, tag: PdfDocumentMetadataTagType) -> Option<String> {
    let v = md.get(tag)?.value().to_string();
    (!v.trim().is_empty()).then_some(v)
}

// ---------------------------------------------------------------------------
// extract_pdf_metadata — catch-and-fall-through over the whole pipeline
// ---------------------------------------------------------------------------

/// SYNCHRONOUS, BLOCKING native FFI — async callers MUST run it via
/// `tokio::task::spawn_blocking` (see `resolve_pdf_metadata`) so it neither stalls
/// a runtime worker nor blocks on the per-call libpdfium lock from an executor.
pub(crate) fn extract_pdf_metadata(bytes: &[u8]) -> Extracted {
    // Bind a fresh Pdfium, extract, and drop it within this call (see `bind_pdfium`
    // for the lock mechanism that makes a short-lived instance the correct choice).
    // catch_unwind degrades a pdfium *panic* to all-None — but only under an unwind
    // profile; NOTE (D30): in a release build (`panic = "abort"`) a panic aborts the
    // process, and a native libpdfium *segfault* is uncatchable in either profile.
    // Production should run extraction behind a worker/subprocess boundary.
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let Some(pdfium) = bind_pdfium() else {
            return Extracted::default();
        };
        let Ok(doc) = pdfium.load_pdf_from_byte_slice(bytes, None) else {
            return Extracted::default();
        };
        extract_from_doc(&doc)
    }))
    .unwrap_or_default()
}

fn extract_from_doc(doc: &PdfDocument) -> Extracted {
    let md = doc.metadata();
    let mut title = meta_get(&md, PdfDocumentMetadataTagType::Title);
    let mut authors = meta_get(&md, PdfDocumentMetadataTagType::Author);
    let date_str = meta_get(&md, PdfDocumentMetadataTagType::CreationDate)
        .or_else(|| meta_get(&md, PdfDocumentMetadataTagType::ModificationDate));

    if title.as_deref().is_some_and(looks_autogenerated) {
        title = None;
    }
    if authors.as_deref().is_some_and(looks_junk_author) {
        authors = None;
    }

    // First-page text — Python reads pages[0]. pdfium emits proper newlines, so
    // the title heuristic sees one logical line per visual line (no length guard
    // needed, unlike lopdf).
    let first_page = doc
        .pages()
        .first()
        .ok()
        .and_then(|p| p.text().ok().map(|t| t.all()))
        .unwrap_or_default();

    let doi = extract_doi(&first_page);
    let arxiv_id = extract_arxiv_id(&first_page);

    if title.is_none() && !first_page.is_empty() {
        title = extract_title_from_text(&first_page);
    }

    let year = date_str.as_deref().and_then(parse_year);

    Extracted {
        title,
        authors,
        doi,
        arxiv_id,
        year,
    }
}

// ---------------------------------------------------------------------------
// Local source id:  local:<sha256(bytes)[:16 hex]>
// ---------------------------------------------------------------------------

fn pdf_source_id(bytes: &[u8]) -> String {
    let h = sha256(bytes);
    let mut s = String::from("local:");
    for byte in &h[..8] {
        use std::fmt::Write;
        let _ = write!(s, "{byte:02x}");
    }
    s
}

// ---------------------------------------------------------------------------
// resolve_pdf_metadata — the seam `import_pdf` injects
// ---------------------------------------------------------------------------

/// Build a `PaperMetadata` from PDF bytes. Returns `(meta, external_identity)`:
/// `meta` always carries a `local:<sha256>` source_id (imports are local-first);
/// `external_identity` is the upstream `(source_id, version)` when enrichment
/// matched, else None.
///
/// Async because enrichment hits the network (arXiv/DOI/CrossRef); `data_dir`
/// threads through to `arxiv_get`'s rate-limit file. When no upstream matches it
/// returns the partial-from-extraction record + `None` (Python's fallthrough).
pub async fn resolve_pdf_metadata(
    bytes: &[u8],
    data_dir: &Path,
) -> Result<(PaperMetadata, Option<(String, i64)>)> {
    // Blocking native FFI — off the executor onto the blocking pool (and the
    // per-call libpdfium lock is waited on there, not on a runtime worker).
    let owned = bytes.to_vec();
    let raw = tokio::task::spawn_blocking(move || extract_pdf_metadata(&owned))
        .await
        .unwrap_or_default();
    let local_id = pdf_source_id(bytes);

    // Enrich from an upstream record when an arXiv id / DOI / title matches.
    // external_identity = (enriched.source_id, version) so the importer can
    // dedupe against an existing root; the returned meta keeps the local id.
    if let Some(enriched) = enrich_external(&raw, data_dir).await {
        let external = (!enriched.source_id.is_empty())
            .then(|| (enriched.source_id.clone(), enriched.version));
        let meta = PaperMetadata {
            source_id: local_id,
            version: 1,
            title: if enriched.title.is_empty() {
                raw.title.clone().unwrap_or_default()
            } else {
                enriched.title
            },
            authors: enriched.authors,
            published: enriched.published,
            updated: None,
            summary: enriched.summary,
            category: enriched.category,
            categories: None,
            doi: enriched.doi,
            journal_ref: None,
            comment: None,
            url: enriched.url,
            tags: None,
            source: Some("pdf".into()),
        };
        return Ok((meta, external));
    }

    // No enrichment: partial record from extraction (Python's final fallthrough).
    let authors: Vec<String> = raw
        .authors
        .as_deref()
        .map(|a| {
            a.split(';')
                .map(str::trim)
                .filter(|p| !p.is_empty())
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();

    let published = raw
        .year
        .and_then(|y| NaiveDate::from_ymd_opt(y, 1, 1))
        .unwrap_or_else(|| Utc::now().date_naive());

    let meta = PaperMetadata {
        source_id: local_id,
        version: 1,
        title: raw.title.unwrap_or_default(),
        authors,
        published,
        updated: None,
        summary: String::new(),
        category: None,
        categories: None,
        doi: None,
        journal_ref: None,
        comment: None,
        url: None,
        tags: None,
        source: Some("pdf".into()),
    };
    Ok((meta, None))
}

/// Upstream enrichment dispatch (first hit wins): arXiv id -> arxiv::fetch_by_id,
/// DOI -> doi_resolve::resolve_doi, title -> CrossRef title search. Every source
/// error is swallowed and the next is tried (Python catches and falls through);
/// `None` means nothing matched and the caller keeps the partial record.
async fn enrich_external(raw: &Extracted, data_dir: &Path) -> Option<PaperMetadata> {
    if let Some(id) = &raw.arxiv_id {
        if let Ok(m) = arxiv::fetch_by_id(id, data_dir).await {
            return Some(m);
        }
    }
    if let Some(doi) = &raw.doi {
        if let Ok(m) = doi_resolve::resolve_doi(doi, data_dir).await {
            return Some(m);
        }
    }
    if let Some(title) = &raw.title {
        if let Some(m) = try_crossref_title(title, data_dir).await {
            return Some(m);
        }
    }
    None
}

/// CrossRef title search (Python `_try_crossref_title`): take the first candidate
/// whose title is >= 0.5 Jaccard-similar; if it carries a DOI, upgrade via
/// `resolve_doi` (gets the arXiv record when available), else return it as-is.
async fn try_crossref_title(title: &str, data_dir: &Path) -> Option<PaperMetadata> {
    for candidate in crossref::search_by_title(title, 3).await {
        if !candidate.title.is_empty() && title_similarity(title, &candidate.title) >= 0.5 {
            if let Some(doi) = &candidate.doi {
                if let Ok(m) = doi_resolve::resolve_doi(doi, data_dir).await {
                    return Some(m);
                }
            }
            return Some(candidate);
        }
    }
    None
}

// ---------------------------------------------------------------------------
// sha256 — no `sha2` direct dep in this crate (it's transitive-only) and
// Cargo.toml is off-limits, so a self-contained impl. FIPS-180-4; checked
// against the empty-string vector in tests.
// ---------------------------------------------------------------------------

fn sha256(data: &[u8]) -> [u8; 32] {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];

    let bit_len = (data.len() as u64) * 8;
    let mut msg = data.to_vec();
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    let mut w = [0u32; 64];
    for chunk in msg.chunks_exact(64) {
        for (i, word) in chunk.chunks_exact(4).enumerate() {
            w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let mut v = h;
        for i in 0..64 {
            let s1 = v[4].rotate_right(6) ^ v[4].rotate_right(11) ^ v[4].rotate_right(25);
            let ch = (v[4] & v[5]) ^ ((!v[4]) & v[6]);
            let t1 = v[7]
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = v[0].rotate_right(2) ^ v[0].rotate_right(13) ^ v[0].rotate_right(22);
            let maj = (v[0] & v[1]) ^ (v[0] & v[2]) ^ (v[1] & v[2]);
            let t2 = s0.wrapping_add(maj);
            v = [
                t1.wrapping_add(t2),
                v[0],
                v[1],
                v[2],
                v[3].wrapping_add(t1),
                v[4],
                v[5],
                v[6],
            ];
        }
        for i in 0..8 {
            h[i] = h[i].wrapping_add(v[i]);
        }
    }

    let mut out = [0u8; 32];
    for (i, word) in h.iter().enumerate() {
        out[i * 4..i * 4 + 4].copy_from_slice(&word.to_be_bytes());
    }
    out
}

// ---------------------------------------------------------------------------
// Tests — pure scanners + the D10 spike against the committed real PDFs.
// No network: enrichment is not exercised here.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ---- pure scanners ----

    #[test]
    fn doi_scanner() {
        assert_eq!(
            extract_doi("See doi: 10.1234/journal.abc for details.").as_deref(),
            Some("10.1234/journal.abc")
        );
        assert_eq!(
            extract_doi("Published at 10.1234/xyz.456.").as_deref(),
            Some("10.1234/xyz.456")
        );
        assert_eq!(
            extract_doi("Reference (10.1234/foo)").as_deref(),
            Some("10.1234/foo")
        );
        assert_eq!(
            extract_doi("10.48550/arXiv.2204.12985 was accepted.").as_deref(),
            Some("10.48550/arXiv.2204.12985")
        );
        assert_eq!(extract_doi("No DOI in this text."), None);
        assert_eq!(extract_doi("10.123/short"), None); // <4-digit registrant
    }

    #[test]
    fn arxiv_scanner() {
        assert_eq!(
            extract_arxiv_id("arXiv:2411.10406v2").as_deref(),
            Some("2411.10406v2")
        );
        assert_eq!(
            extract_arxiv_id("arXiv:2204.12985").as_deref(),
            Some("2204.12985")
        );
        assert_eq!(
            extract_arxiv_id("arxiv:2204.12985v1").as_deref(),
            Some("2204.12985v1")
        );
        assert_eq!(
            extract_arxiv_id("Submitted to arXiv:2411.10406v2 for review").as_deref(),
            Some("2411.10406v2")
        );
        assert_eq!(extract_arxiv_id("No arXiv ID here."), None);
        assert_eq!(
            extract_arxiv_id("arXiv:2204.12345v1").as_deref(),
            Some("2204.12345v1")
        );
    }

    #[test]
    fn autogenerated_and_junk_filters() {
        assert!(looks_autogenerated("Microsoft Word - Document1"));
        assert!(looks_autogenerated("Untitled"));
        assert!(looks_autogenerated("PowerPoint Presentation"));
        assert!(looks_autogenerated("   "));
        assert!(looks_autogenerated("microsoft word doc"));
        assert!(!looks_autogenerated("Attention Is All You Need"));

        assert!(looks_junk_author("Windows User"));
        assert!(looks_junk_author("User"));
        assert!(!looks_junk_author("Jane Doe"));
    }

    #[test]
    fn similarity_jaccard() {
        assert_eq!(
            title_similarity("Attention Is All You Need", "Attention Is All You Need"),
            1.0
        );
        assert_eq!(
            title_similarity("Alpha Beta Gamma", "Delta Epsilon Zeta"),
            0.0
        );
        let s = title_similarity("Deep Learning Models", "Deep Neural Learning");
        assert!(s > 0.0 && s < 1.0);
        assert_eq!(title_similarity("Hello World", "hello world"), 1.0);
        assert_eq!(title_similarity("", "anything"), 0.0);
    }

    #[test]
    fn title_heuristic_stops() {
        // blank line after content ends the block
        assert_eq!(
            extract_title_from_text("Title Line One\nTitle Line Two\n\nbody body").as_deref(),
            Some("Title Line One Title Line Two")
        );
        // author-list line ends the block
        assert_eq!(
            extract_title_from_text("Real Title\nMohseni,1 and Others\nmore").as_deref(),
            Some("Real Title")
        );
        // caps at 3 lines
        assert_eq!(
            extract_title_from_text("a\nb\nc\nd\ne").as_deref(),
            Some("a b c")
        );
        assert_eq!(extract_title_from_text("\n\n  \n"), None);
    }

    #[test]
    fn year_parser() {
        assert_eq!(parse_year("D:20210315120000"), Some(2021));
        assert_eq!(parse_year("D:18990101"), None); // implausible
        assert_eq!(parse_year("no digits"), None);
    }

    #[test]
    fn sha256_known_vector() {
        // sha256("") = e3b0c442...; pdf id keeps the first 16 hex chars.
        assert_eq!(&pdf_source_id(b"")[..22], "local:e3b0c44298fc1c14");
        assert_eq!(
            pdf_source_id(b"stable pdf bytes"),
            // sha256("stable pdf bytes")[:16]
            format!("local:{}", &hex(&sha256(b"stable pdf bytes"))[..16])
        );
    }

    fn hex(b: &[u8]) -> String {
        b.iter().map(|x| format!("{x:02x}")).collect()
    }

    // ---- partial-record builder ----

    // Junk bytes extract no arXiv id / DOI / title, so enrich_external short-
    // circuits to None with zero network calls — the offline fallthrough path.
    #[tokio::test]
    async fn resolve_partial_record_shape() {
        let dir = tempfile::tempdir().unwrap();
        let (m, ext) = resolve_pdf_metadata(b"some pdf bytes", dir.path())
            .await
            .unwrap();
        assert_eq!(ext, None);
        assert_eq!(m.source.as_deref(), Some("pdf"));
        assert!(m.source_id.starts_with("local:"));
        // deterministic id == local:<sha256[:16]>
        assert_eq!(
            m.source_id,
            format!("local:{}", &hex(&sha256(b"some pdf bytes"))[..16])
        );
    }

    // ---- D10 SPIKE: real committed PDFs (pdfium extraction, no network) ----

    fn read_test_pdf(name: &str) -> Vec<u8> {
        let p = format!(
            "{}/../../../tests/test_file/{name}",
            env!("CARGO_MANIFEST_DIR")
        );
        std::fs::read(&p).unwrap_or_else(|e| panic!("read {p}: {e}"))
    }

    // D10 RESOLVED: pdf-extract rendered this 76-page/29MB paper's first page in
    // ~183s; pdfium does it in ~0.3s (vs lopdf ~5s). Fast enough to run inline.
    // The arXiv id is the load-bearing extraction: it drives enrichment, which
    // supplies the real title/authors.
    #[test]
    fn spike_multi_author_2411_fast() {
        let m = extract_pdf_metadata(&read_test_pdf("2411.10406v2.pdf"));
        assert_eq!(m.arxiv_id.as_deref(), Some("2411.10406v2"));
    }

    #[test]
    fn spike_embedded_meta_2604_21547() {
        let m = extract_pdf_metadata(&read_test_pdf("2604.21547v1.pdf"));
        assert_eq!(m.arxiv_id.as_deref(), Some("2604.21547v1"));
        assert!(
            m.title.as_deref().unwrap_or("").contains("Yang-Baxter"),
            "got title: {:?}",
            m.title
        );
        assert_eq!(m.authors.as_deref(), Some("Vinayak M. Kulkarni"));
        assert_eq!(m.doi, None);
    }

    #[test]
    fn spike_junk_author_2604_00068() {
        let m = extract_pdf_metadata(&read_test_pdf("2604.00068v2.pdf"));
        let title = m.title.expect("text-heuristic title");
        assert!(title.contains("Chandrasekhar"), "got title: {title:?}");
        assert_eq!(m.authors, None, "OS-junk author filtered out");
        assert_eq!(m.doi, None);
    }

    // Non-arXiv PDF (no arXiv-id/DOI to enrich from): the text-title heuristic is
    // the ONLY metadata, so a regression here is silent — guards that the title
    // doesn't swallow the page (pdfium's proper newlines keep it one line per
    // visual line). Asserts byte-parity with the Python/pypdf baseline for paper.pdf.
    #[test]
    fn non_arxiv_text_title_is_bounded() {
        let m = extract_pdf_metadata(&read_test_pdf("paper.pdf"));
        let title = m.title.expect("text-heuristic title");
        assert!(
            title.chars().count() < 200,
            "title swallowed the page: {} chars",
            title.chars().count()
        );
        assert!(
            title.starts_with("Note on the construction"),
            "got: {title:?}"
        );
    }

    // Regression for the thread_local deadlock: pdfium-render's thread_safe holds a
    // process-global lock for a Pdfium's whole lifetime. A per-thread instance pinned
    // it (the 2nd concurrent extraction blocked forever on a long-lived worker); the
    // per-call bind+drop releases it. 8 concurrent resolves on a 4-worker runtime must
    // all finish — the timeout turns a regression into a failure, not a hung suite.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn concurrent_extractions_do_not_deadlock() {
        let dir = tempfile::tempdir().unwrap();
        let mut handles = Vec::new();
        for i in 0..8 {
            let p = dir.path().to_path_buf();
            handles.push(tokio::spawn(async move {
                // Each call binds a Pdfium (acquires the global lock) and drops it.
                let bytes = format!("%PDF junk {i}").into_bytes();
                resolve_pdf_metadata(&bytes, &p).await
            }));
        }
        let join_all = async {
            for h in handles {
                h.await.unwrap().unwrap();
            }
        };
        tokio::time::timeout(std::time::Duration::from_secs(30), join_all)
            .await
            .expect("concurrent PDF extractions deadlocked (timed out)");
    }

    #[tokio::test]
    async fn malformed_pdf_degrades_not_panics() {
        // catch-and-fall-through: garbage in -> all-None, no panic.
        let m = extract_pdf_metadata(b"%PDF-1.4 not really a pdf");
        assert_eq!(m, Extracted::default());
        // resolve still yields a partial record (deterministic local id); no
        // arXiv/DOI/title extracted, so enrichment makes no network call.
        let dir = tempfile::tempdir().unwrap();
        let (meta, ext) = resolve_pdf_metadata(b"%PDF junk", dir.path())
            .await
            .unwrap();
        assert!(meta.source_id.starts_with("local:"));
        assert_eq!(ext, None);
    }
}
