// Generated by `npm run types:gen` from the #[derive(TS)] serializers in
// linxiv-core. DO NOT EDIT — `npm run types:check` fails when this file drifts
// from the Rust source. Frontend-facing aliases and the shapes that have no
// single Rust struct live in ./api.ts.

export type PaperDetails = {
  paper_id: number,
  source_id: string,
  version: number,
  title: string,
  summary: string | null,
  published: string | null,
  updated: string | null,
  url: string | null,
  doi: string | null,
  category: string | null,
  categories: Array<string>,
  journal_ref: string | null,
  comment: string | null,
  authors: Array<string>,
  tags: Array<string>,
  has_pdf: boolean,
  pdf_path: string | null,
  source: string | null,
  downloaded_source: boolean,
  /**
   * Never null: PAPER.SOURCE_FK is NOT NULL and every reader selects from
   * the `papers` view.
   */
  source_fk: number,
};

export type SearchResultOut = {
  source_id: string,
  version: number,
  title: string,
  summary: string,
  authors: Array<string>,
  /**
   * "" when the published date is the `date.min` sentinel; else ISO date.
   */
  published: string,
  paper_url: string,
  primary_category: string,
  /**
   * The full namespaced source_id (kept, unlike the stripped `source_id`).
   */
  entry_id: string,
};

export type Status = "active" | "archived" | "deleted";

export type ProjectOut = {
  /**
   * Never null: `ProjectDetails.id` is optional only because that struct
   * doubles as the pre-insert shape; `to_out` refuses a row without an id.
   */
  id: number,
  name: string,
  description: string,
  color_hex: string | null,
  project_tags: Array<string>,
  source_ids: Array<string>,
  paper_count: number,
  status: Status,
  created_at: string | null,
  updated_at: string | null,
  archived_at: string | null,
  share_id: string | null,
};

export type NoteDetails = {
  /**
   * NOTE_SK is the primary key; a read row always has one.
   */
  id: number,
  /**
   * Stable identity (uuid v4) surviving export/import + share.
   */
  uuid: string,
  source_fk: number,
  paper_id_fk: number | null,
  project_id: number | null,
  title: string,
  content: string,
  created_at: string | null,
  updated_at: string | null,
};

export type AnnotationDetails = {
  id: number,
  /**
   * Stable identity (uuid v4) surviving export/import + share.
   */
  uuid: string,
  source_fk: number,
  project_id: number | null,
  anchor: string,
  comment: string,
  created_at: string | null,
  updated_at: string | null,
};

export type BasicAuthorDetails = {
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type AuthorWithCount = {
  paper_count: number,
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type AuthorPaperPreview = {
  paper_id: number,
  source_id: string,
  source_fk: number,
  version: number,
  title: string | null,
};

export type AuthorWithPapers = {
  paper_count: number,
  papers: Array<AuthorPaperPreview>,
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type Stats = {
  paper_count: number,
  tag_count: number,
  category_count: number,
  pdf_count: number,
  recent_papers: Array<PaperDetails>,
};

export type DoiVersionCandidate = {
  source_fk: number,
  source_id: string,
  title: string,
  source: string | null,
  published: string | null,
  doi: string,
};

export type FullTextReceipt = {
  source_id: string,
  version: number,
  indexed: boolean,
  chars?: number,
  reason?: string,
};

export type PaperMembershipReceipt = {
  ok: boolean,
  project_id: number,
  paper_id: string,
  paper_count: number,
};

export type BibtexImportReceipt = {
  saved_count: number,
  source_ids: Array<string>,
};

export type FilterField = "TITLE" | "SUMMARY" | "AUTHOR";

export type FilterAction = "DENY" | "ALLOW";

export type FilterRule = {
  rule_id: number,
  field: FilterField,
  keywords: string,
  action: FilterAction,
  enabled: boolean,
};
