#!/usr/bin/env bash
# Snapshot the exact fresh-install schema at a given git ref, by actually
# building and running that ref's real init_db (crates/core/examples/
# snapshot_schema.rs), not a hand-typed reconstruction. Run this once after
# tagging every release, then commit the output into the private
# linxiv-comprehensive-documentation repo's schemas/ dir (never into this
# public repo -- see that repo's schemas/README.md for why).
#
# Only works from the point this script + the example exist onward (this
# branch). v0.1.0/v0.1.1/v0.1.2-dev/v0.2.0 predate the Rust schema entirely
# (no src-tauri/crates/core at those tags) -- there's nothing to snapshot
# there; the pre-Rust-port shape those releases used is already hand-captured
# by the legacy-schema tests in crates/core/src/storage/migrations.rs.
#
# Usage: scripts/snapshot_schema.sh <git-ref> <output-dir>
#   scripts/snapshot_schema.sh v0.3.0 ../linxiv-comprehensive-documentation/schemas
set -euo pipefail

REF="${1:?usage: snapshot_schema.sh <git-ref> <output-dir>}"
OUT_DIR="${2:?usage: snapshot_schema.sh <git-ref> <output-dir>}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKTREE="$(mktemp -d)"
TMP_OUT=""
cleanup() {
  git -C "$ROOT" worktree remove --force "$WORKTREE" >/dev/null 2>&1 || true
  rm -rf "$WORKTREE"
  [ -n "$TMP_OUT" ] && rm -f "$TMP_OUT"
}
trap cleanup EXIT

# `--` guards against a ref starting with `-` being parsed as an option.
git -C "$ROOT" worktree add --detach --quiet "$WORKTREE" -- "$REF"

mkdir -p "$OUT_DIR"
SAFE_REF="$(echo "$REF" | tr '/' '_')"
OUT_FILE="$OUT_DIR/$SAFE_REF.sql"
# Same directory as OUT_FILE so the final `mv` is a same-filesystem rename
# (atomic) rather than a cross-filesystem copy+unlink that could itself leave
# a partial file behind if interrupted mid-copy.
TMP_OUT="$(mktemp "$OUT_DIR/.$SAFE_REF.XXXXXX.tmp")"

{
  # `git rev-parse -- "$REF"` would NOT resolve a SHA here -- everything after
  # `--` is a pathspec, not a revision, so that prints "--\n$REF" instead of a
  # commit hash. Resolve HEAD of the worktree instead, which is already
  # checked out at $REF (detached) above.
  echo "-- linXiv fresh-install schema at $REF ($(git -C "$WORKTREE" rev-parse HEAD))"
  echo "-- generated by scripts/snapshot_schema.sh; do not hand-edit"
  echo
  (cd "$WORKTREE/src-tauri" && cargo run --quiet -p linxiv-core --example snapshot_schema)
} > "$TMP_OUT"
# Only replace the real output on success -- a failed run (e.g. this ref
# predates the Rust schema and has no linxiv-core example to run) must never
# leave a half-written file that looks like a valid, if sparse, snapshot.
mv "$TMP_OUT" "$OUT_FILE"

echo "Wrote $OUT_FILE"
