//! pdfium binding, native library discovery, and in-process extraction.

use std::sync::OnceLock;

use pdfium_render::prelude::*;

use super::scan::{
    extract_arxiv_id, extract_doi, extract_title_from_text, looks_autogenerated, looks_junk_author,
    parse_year,
};

// ---------------------------------------------------------------------------
// Raw extraction result (`abstract` is always None).
// ---------------------------------------------------------------------------

#[derive(Debug, Default, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(default)]
pub(crate) struct Extracted {
    pub title: Option<String>,
    pub authors: Option<String>,
    pub doi: Option<String>,
    pub arxiv_id: Option<String>,
    pub year: Option<i32>,
}

// ---------------------------------------------------------------------------
// pdfium binding + Info dict + first-page text
// ---------------------------------------------------------------------------

/// Resolve the libpdfium path ONCE. Order: `LINXIV_PDFIUM_LIB` env → `pdfium/`
/// next to the executable → (debug builds only) the dev vendor dir; `None` → the
/// system library at bind time. The vendor path is `cfg(debug_assertions)`-gated
/// so it can't be baked into a shipped binary.
pub(crate) fn pdfium_lib_path() -> Option<&'static std::path::Path> {
    static LIB: OnceLock<Option<std::path::PathBuf>> = OnceLock::new();
    LIB.get_or_init(|| {
        let in_dir = |dir: std::path::PathBuf| {
            let p = Pdfium::pdfium_platform_library_name_at_path(&dir);
            p.exists().then_some(p)
        };
        if let Some(p) = std::env::var_os("LINXIV_PDFIUM_LIB") {
            return Some(std::path::PathBuf::from(p));
        }
        if let Some(p) = std::env::current_exe()
            .ok()
            .and_then(|e| e.parent().map(|d| d.join("pdfium")))
            .and_then(in_dir)
        {
            return Some(p);
        }
        #[cfg(debug_assertions)]
        if let Some(p) = in_dir(std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../vendor/pdfium/lib"
        ))) {
            return Some(p);
        }
        None
    })
    .as_deref()
}

/// Bind libpdfium for a SINGLE extraction; per-call bind+drop releases the
/// process-global lock each time (see concurrent_extractions_do_not_deadlock).
fn bind_pdfium() -> Option<Pdfium> {
    let bindings = match pdfium_lib_path() {
        Some(p) => Pdfium::bind_to_library(p).ok(),
        None => Pdfium::bind_to_system_library().ok(),
    };
    match bindings {
        Some(b) => Some(Pdfium::new(b)),
        None => {
            static WARNED: std::sync::Once = std::sync::Once::new();
            WARNED.call_once(|| {
                tracing::error!(
                    "libpdfium not found — PDF metadata extraction disabled; run \
                     scripts/fetch_pdfium.sh or set LINXIV_PDFIUM_LIB"
                )
            });
            None
        }
    }
}

/// Non-empty Info-dict value for `tag`, else None; capped at 300 chars.
fn meta_get(md: &PdfMetadata, tag: PdfDocumentMetadataTagType) -> Option<String> {
    let v = md.get(tag)?.value().to_string();
    let capped: String = v.chars().take(300).collect();
    (!capped.trim().is_empty()).then_some(capped)
}

// ---------------------------------------------------------------------------
// extract_pdf_metadata — catch-and-fall-through over the whole pipeline
// ---------------------------------------------------------------------------

/// SYNCHRONOUS, BLOCKING native FFI — async callers MUST run it via
/// `tokio::task::spawn_blocking` (see `resolve_pdf_metadata`) so it neither stalls
/// a runtime worker nor blocks on the per-call libpdfium lock from an executor.
pub(crate) fn extract_pdf_metadata(bytes: &[u8]) -> Extracted {
    // Bind a fresh Pdfium, extract, and drop it within this call (see `bind_pdfium`
    // for the lock mechanism that makes a short-lived instance the correct choice).
    // catch_unwind degrades a pdfium *panic* to all-None — but only under an unwind
    // profile; NOTE (D30): in a release build (`panic = "abort"`) a panic aborts the
    // process, and a native libpdfium *segfault* is uncatchable in either profile.
    // `extract_pdf_metadata_isolated` is the subprocess boundary covering those.
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let Some(pdfium) = bind_pdfium() else {
            return Extracted::default();
        };
        let Ok(doc) = pdfium.load_pdf_from_byte_slice(bytes, None) else {
            return Extracted::default();
        };
        extract_from_doc(&doc)
    }))
    .unwrap_or_default()
}

fn extract_from_doc(doc: &PdfDocument) -> Extracted {
    let md = doc.metadata();
    let mut title = meta_get(md, PdfDocumentMetadataTagType::Title);
    let mut authors = meta_get(md, PdfDocumentMetadataTagType::Author);
    let date_str = meta_get(md, PdfDocumentMetadataTagType::CreationDate)
        .or_else(|| meta_get(md, PdfDocumentMetadataTagType::ModificationDate));

    if title.as_deref().is_some_and(looks_autogenerated) {
        title = None;
    }
    if authors.as_deref().is_some_and(looks_junk_author) {
        authors = None;
    }

    // First-page text only. pdfium emits proper newlines, so the title heuristic
    // sees one logical line per visual line; joined output is capped at 300 chars
    // in extract_title_from_text.
    let first_page = doc
        .pages()
        .first()
        .ok()
        .and_then(|p| p.text().ok().map(|t| t.all()))
        .unwrap_or_default();

    let doi = extract_doi(&first_page);
    let arxiv_id = extract_arxiv_id(&first_page);

    if title.is_none() && !first_page.is_empty() {
        title = extract_title_from_text(&first_page);
    }

    let year = date_str.as_deref().and_then(parse_year);

    Extracted {
        title,
        authors,
        doi,
        arxiv_id,
        year,
    }
}

// ---------------------------------------------------------------------------
// Tests — the D10 spike against the committed real PDFs. No network:
// enrichment is not exercised here. The D10 spikes skip (not panic) when
// libpdfium or a fixture is unavailable — see `load_spike_pdf`.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sources::pdf_metadata::resolve_pdf_metadata;

    // ---- D10 SPIKE: real committed PDFs (pdfium extraction, no network) ----

    // Skip guard (not panic) for the spike tests below: a dev checkout without
    // `scripts/fetch_pdfium.sh` run (no libpdfium) or a shallow/sparse checkout
    // missing the committed fixture shouldn't fail the suite, per this repo's
    // fixture-gating convention — print why and return `None` for the caller to
    // early-return on, same as `bind_pdfium`'s own missing-library warning.
    fn load_spike_pdf(name: &str) -> Option<Vec<u8>> {
        if bind_pdfium().is_none() {
            eprintln!(
                "skipping {name}: libpdfium not available (run scripts/fetch_pdfium.sh or set LINXIV_PDFIUM_LIB)"
            );
            return None;
        }
        let p = format!(
            "{}/../../../tests/test_file/{name}",
            env!("CARGO_MANIFEST_DIR")
        );
        match std::fs::read(&p) {
            Ok(b) => Some(b),
            Err(e) => {
                eprintln!("skipping {name}: fixture not found ({p}): {e}");
                None
            }
        }
    }

    // D10 RESOLVED: pdf-extract rendered this 76-page/29MB paper's first page in
    // ~183s; pdfium does it in ~0.3s (vs lopdf ~5s). Fast enough to run inline.
    // The arXiv id is the load-bearing extraction: it drives enrichment, which
    // supplies the real title/authors.
    #[test]
    fn spike_multi_author_2411_fast() {
        let Some(bytes) = load_spike_pdf("2411.10406v2.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        assert_eq!(m.arxiv_id.as_deref(), Some("2411.10406v2"));
    }

    #[test]
    fn spike_embedded_meta_2604_21547() {
        let Some(bytes) = load_spike_pdf("2604.21547v1.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        assert_eq!(m.arxiv_id.as_deref(), Some("2604.21547v1"));
        assert!(
            m.title.as_deref().unwrap_or("").contains("Yang-Baxter"),
            "got title: {:?}",
            m.title
        );
        assert_eq!(m.authors.as_deref(), Some("Vinayak M. Kulkarni"));
        assert_eq!(m.doi, None);
    }

    #[test]
    fn spike_junk_author_2604_00068() {
        let Some(bytes) = load_spike_pdf("2604.00068v2.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        let title = m.title.expect("text-heuristic title");
        assert!(title.contains("Chandrasekhar"), "got title: {title:?}");
        assert_eq!(m.authors, None, "OS-junk author filtered out");
        assert_eq!(m.doi, None);
    }

    // Non-arXiv PDF (no arXiv-id/DOI to enrich from): the text-title heuristic is
    // the ONLY metadata, so a regression here is silent — guards that the title
    // doesn't swallow the page (pdfium's proper newlines keep it one line per
    // visual line).
    #[test]
    fn non_arxiv_text_title_is_bounded() {
        let Some(bytes) = load_spike_pdf("paper.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        let title = m.title.expect("text-heuristic title");
        assert!(
            title.chars().count() < 200,
            "title swallowed the page: {} chars",
            title.chars().count()
        );
        assert!(
            title.starts_with("Note on the construction"),
            "got: {title:?}"
        );
    }

    // Regression for the thread_local deadlock: pdfium-render's thread_safe holds a
    // process-global lock for a Pdfium's whole lifetime. A per-thread instance pinned
    // it (the 2nd concurrent extraction blocked forever on a long-lived worker); the
    // per-call bind+drop releases it. 8 concurrent resolves on a 4-worker runtime must
    // all finish — the timeout turns a regression into a failure, not a hung suite.
    // Exercises resolve_pdf_metadata's full path (extraction + enrichment) and when
    // LINXIV_PDF_WORKER or an adjacent binary is available, the worker subprocess path.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn concurrent_extractions_do_not_deadlock() {
        let data_dir = tempfile::tempdir().unwrap();
        let mut handles = Vec::new();
        for i in 0..8 {
            let data_dir_path = data_dir.path().to_path_buf();
            handles.push(tokio::spawn(async move {
                // Each call exercises resolve_pdf_metadata's full path (extraction + enrichment).
                // Result value is irrelevant here — only completion (no deadlock) matters.
                let bytes = format!("%PDF junk {i}").into_bytes();
                let _ = resolve_pdf_metadata(&bytes, &data_dir_path, "", true).await;
            }));
        }
        let join_all = async {
            for h in handles {
                h.await.unwrap();
            }
        };
        tokio::time::timeout(std::time::Duration::from_secs(30), join_all)
            .await
            .expect("concurrent PDF extractions deadlocked (timed out)");
    }

    #[tokio::test]
    async fn malformed_pdf_degrades_not_panics() {
        // catch-and-fall-through: garbage in -> all-None, no panic.
        let m = extract_pdf_metadata(b"%PDF-1.4 not really a pdf");
        assert_eq!(m, Extracted::default());
        // resolve still yields a partial record (deterministic local id); no
        // arXiv/DOI/title extracted, so enrichment makes no network call.
        let dir = tempfile::tempdir().unwrap();
        let (meta, ext) = resolve_pdf_metadata(b"%PDF junk", dir.path(), "", true)
            .await
            .unwrap();
        assert!(meta.source_id.starts_with("local:"));
        assert_eq!(ext, None);
    }
}
