//! pdf_metadata — Rust port of `sources/pdf_metadata.py` (D10 spike).
//!
//! Parser over PDF bytes: pdfium (native libpdfium) for first-page text and the
//! Info dict (/Title /Author /CreationDate) — ~22x faster than lopdf on large PDFs
//! with cleaner text (proper newlines). The arXiv-id and
//! DOI scanners, the 3-line title heuristic, and the autogenerated-title /
//! junk-author filters are hand-rolled (no `regex` dep in this crate). Extraction
//! is catch-and-fall-through: a malformed PDF degrades to an all-None record. The
//! catch covers a pdfium *panic* under an unwind profile only — see the D30 note in
//! `extract_pdf_metadata` for the release/`abort` and native-segfault caveats.
//!
//! `resolve_pdf_metadata` builds the local-identity `PaperMetadata`. PDF-metadata-
//! first: the PDF's own title/authors win outright when they're both present
//! (`pdf_metadata_is_sufficient`) — no network call for the fields. A text-scanned
//! arXiv id or DOI is still only a candidate dedupe identity at that point (page 1
//! can cite someone else's paper), so, when the `pdf_import_verify_identity_enabled`
//! setting (default true) is on, `verify_arxiv_identity`/`verify_doi_identity`
//! confirm it over the network before it's trusted — off, and a candidate id is
//! simply never adopted as identity, PDF-metadata-first meaning zero network calls,
//! full stop. Only when the PDF metadata is insufficient does this enrich from an
//! upstream record (arXiv/DOI/CrossRef, see `enrich_external` — not gated by that
//! setting, since it's the only way to get metadata at all in that case), falling
//! back to the Python "all resolution fails" partial when even that finds nothing.
//!
//! Layout: `scan` (hand-rolled byte scanners), `extract` (pdfium FFI + library
//! discovery), `worker` (subprocess crash boundary + JSON IPC), `identity`
//! (local sha256 id), `resolve` (network enrichment orchestration).

mod extract;
mod identity;
mod resolve;
mod scan;
mod worker;

pub use resolve::resolve_pdf_metadata;
pub use worker::{extract_pdf_metadata_json, PDF_META_SUBCOMMAND};
