//! Hand-rolled byte scanners and text heuristics — no `regex` dep in this crate.

use chrono::{Datelike, Utc};

// ---------------------------------------------------------------------------
// Small char-class helpers (\w == [A-Za-z0-9_])
// ---------------------------------------------------------------------------

fn is_word(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

// ---------------------------------------------------------------------------
// arXiv id:  arXiv:(\d{4}\.\d{4,5}(?:v\d+)?)   (case-insensitive)
// ---------------------------------------------------------------------------

/// Length (bytes) of an arXiv id at the start of `b`, or None.
fn match_arxiv(b: &[u8]) -> Option<usize> {
    if b.len() < 5 || !b[..4].iter().all(u8::is_ascii_digit) || b[4] != b'.' {
        return None;
    }
    let ds = 5;
    let mut j = ds;
    while j < b.len() && b[j].is_ascii_digit() && j - ds < 5 {
        j += 1;
    }
    if j - ds < 4 {
        return None; // \d{4,5}
    }
    if j < b.len() && (b[j] == b'v' || b[j] == b'V') {
        let mut m = j + 1;
        while m < b.len() && b[m].is_ascii_digit() {
            m += 1;
        }
        if m > j + 1 {
            j = m; // only consume `v` if followed by \d+
        }
    }
    Some(j)
}

pub(crate) fn extract_arxiv_id(text: &str) -> Option<String> {
    let lower = text.to_ascii_lowercase();
    let lb = lower.as_bytes();
    let tb = text.as_bytes();
    let mut i = 0;
    while i + 6 <= lb.len() {
        if &lb[i..i + 6] == b"arxiv:" {
            let s = i + 6;
            if let Some(len) = match_arxiv(&tb[s..]) {
                return Some(text[s..s + len].to_string());
            }
        }
        i += 1;
    }
    None
}

// ---------------------------------------------------------------------------
// DOI:  \b10\.\d{4,}/\S+   then rstrip ".,)"
// ---------------------------------------------------------------------------

pub(crate) fn extract_doi(text: &str) -> Option<String> {
    let b = text.as_bytes();
    let n = b.len();
    let mut i = 0;
    while i + 3 <= n {
        if b[i] == b'1' && b[i + 1] == b'0' && b[i + 2] == b'.' {
            let boundary = i == 0 || !is_word(b[i - 1]); // \b
            if boundary {
                let ds = i + 3;
                let mut j = ds;
                while j < n && b[j].is_ascii_digit() {
                    j += 1;
                }
                if j - ds >= 4 && j < n && b[j] == b'/' {
                    let mut k = j + 1;
                    while k < n && !b[k].is_ascii_whitespace() {
                        k += 1;
                    }
                    if k > j + 1 {
                        let raw = &text[i..k];
                        let cleaned = raw.trim_end_matches(['.', ',', ')']);
                        return Some(cleaned.to_string());
                    }
                }
            }
        }
        i += 1;
    }
    None
}

// ---------------------------------------------------------------------------
// Title heuristic + junk filters
// ---------------------------------------------------------------------------

pub(crate) fn looks_autogenerated(title: &str) -> bool {
    if title.trim().is_empty() {
        return true; // ^\s*$
    }
    let lt = title.to_ascii_lowercase();
    lt.starts_with("microsoft word") || lt.starts_with("untitled") || lt.starts_with("powerpoint")
}

/// `\bWindows\b` anywhere, or the whole string == User/Admin/Benutzer/Utilisateur.
pub(crate) fn looks_junk_author(author: &str) -> bool {
    let la = author.to_ascii_lowercase();
    let t = la.trim();
    if matches!(t, "user" | "admin" | "benutzer" | "utilisateur") {
        return true;
    }
    la.split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
        .any(|w| w == "windows")
}

/// `\b[A-Z][a-z]+,\s*\d` — a surname-then-affiliation-superscript line.
fn is_author_line(s: &str) -> bool {
    let b = s.as_bytes();
    let n = b.len();
    for i in 0..n {
        if !b[i].is_ascii_uppercase() || (i > 0 && is_word(b[i - 1])) {
            continue;
        }
        let mut j = i + 1;
        while j < n && b[j].is_ascii_lowercase() {
            j += 1;
        }
        if j == i + 1 || j >= n || b[j] != b',' {
            continue; // need [a-z]+ then ','
        }
        let mut k = j + 1;
        while k < n && (b[k] == b' ' || b[k] == b'\t') {
            k += 1; // \s*
        }
        if k < n && b[k].is_ascii_digit() {
            return true;
        }
    }
    false
}

pub(crate) fn extract_title_from_text(text: &str) -> Option<String> {
    let mut lines: Vec<&str> = Vec::new();
    for raw in text.lines() {
        let s = raw.trim();
        if s.is_empty() {
            if !lines.is_empty() {
                break; // blank line after content — title block ended
            }
            continue; // leading blank
        }
        if is_author_line(s) {
            break;
        }
        lines.push(s);
        if lines.len() == 3 {
            break;
        }
    }
    if lines.is_empty() {
        None
    } else {
        let joined = lines.join(" ");
        let capped: String = joined.chars().take(300).collect();
        Some(capped)
    }
}

// ---------------------------------------------------------------------------
// Jaccard title similarity (used by deferred CrossRef enrichment).
// ---------------------------------------------------------------------------

fn words(s: &str) -> std::collections::HashSet<String> {
    s.split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .filter(|w| !w.is_empty())
        .map(|w| w.chars().flat_map(char::to_lowercase).collect())
        .collect()
}

pub(crate) fn title_similarity(a: &str, b: &str) -> f64 {
    let wa = words(a);
    let wb = words(b);
    if wa.is_empty() || wb.is_empty() {
        return 0.0;
    }
    wa.intersection(&wb).count() as f64 / wa.union(&wb).count() as f64
}

// ---------------------------------------------------------------------------
// Year from a PDF date string (first 4-digit run, validated 1900..=now+1).
// ---------------------------------------------------------------------------

pub(crate) fn parse_year(date_str: &str) -> Option<i32> {
    let b = date_str.as_bytes();
    let mut i = 0;
    while i + 4 <= b.len() {
        if b[i..i + 4].iter().all(u8::is_ascii_digit) {
            let y: i32 = std::str::from_utf8(&b[i..i + 4]).ok()?.parse().ok()?;
            // Python does a single re.search then validates; out-of-range -> None.
            return (1900..=Utc::now().year() + 1).contains(&y).then_some(y);
        }
        i += 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- pure scanners ----

    #[test]
    fn doi_scanner() {
        assert_eq!(
            extract_doi("See doi: 10.1234/journal.abc for details.").as_deref(),
            Some("10.1234/journal.abc")
        );
        assert_eq!(
            extract_doi("Published at 10.1234/xyz.456.").as_deref(),
            Some("10.1234/xyz.456")
        );
        assert_eq!(
            extract_doi("Reference (10.1234/foo)").as_deref(),
            Some("10.1234/foo")
        );
        assert_eq!(
            extract_doi("10.48550/arXiv.2204.12985 was accepted.").as_deref(),
            Some("10.48550/arXiv.2204.12985")
        );
        assert_eq!(extract_doi("No DOI in this text."), None);
        assert_eq!(extract_doi("10.123/short"), None); // <4-digit registrant
    }

    #[test]
    fn arxiv_scanner() {
        assert_eq!(
            extract_arxiv_id("arXiv:2411.10406v2").as_deref(),
            Some("2411.10406v2")
        );
        assert_eq!(
            extract_arxiv_id("arXiv:2204.12985").as_deref(),
            Some("2204.12985")
        );
        assert_eq!(
            extract_arxiv_id("arxiv:2204.12985v1").as_deref(),
            Some("2204.12985v1")
        );
        assert_eq!(
            extract_arxiv_id("Submitted to arXiv:2411.10406v2 for review").as_deref(),
            Some("2411.10406v2")
        );
        assert_eq!(extract_arxiv_id("No arXiv ID here."), None);
        assert_eq!(
            extract_arxiv_id("arXiv:2204.12345v1").as_deref(),
            Some("2204.12345v1")
        );
    }

    #[test]
    fn autogenerated_and_junk_filters() {
        assert!(looks_autogenerated("Microsoft Word - Document1"));
        assert!(looks_autogenerated("Untitled"));
        assert!(looks_autogenerated("PowerPoint Presentation"));
        assert!(looks_autogenerated("   "));
        assert!(looks_autogenerated("microsoft word doc"));
        assert!(!looks_autogenerated("Attention Is All You Need"));

        assert!(looks_junk_author("Windows User"));
        assert!(looks_junk_author("User"));
        assert!(!looks_junk_author("Jane Doe"));
    }

    #[test]
    fn similarity_jaccard() {
        assert_eq!(
            title_similarity("Attention Is All You Need", "Attention Is All You Need"),
            1.0
        );
        assert_eq!(
            title_similarity("Alpha Beta Gamma", "Delta Epsilon Zeta"),
            0.0
        );
        let s = title_similarity("Deep Learning Models", "Deep Neural Learning");
        assert!(s > 0.0 && s < 1.0);
        assert_eq!(title_similarity("Hello World", "hello world"), 1.0);
        assert_eq!(title_similarity("", "anything"), 0.0);
    }

    #[test]
    fn title_heuristic_stops() {
        // blank line after content ends the block
        assert_eq!(
            extract_title_from_text("Title Line One\nTitle Line Two\n\nbody body").as_deref(),
            Some("Title Line One Title Line Two")
        );
        // author-list line ends the block
        assert_eq!(
            extract_title_from_text("Real Title\nMohseni,1 and Others\nmore").as_deref(),
            Some("Real Title")
        );
        // caps at 3 lines
        assert_eq!(
            extract_title_from_text("a\nb\nc\nd\ne").as_deref(),
            Some("a b c")
        );
        assert_eq!(extract_title_from_text("\n\n  \n"), None);
    }

    #[test]
    fn year_parser() {
        assert_eq!(parse_year("D:20210315120000"), Some(2021));
        assert_eq!(parse_year("D:18990101"), None); // implausible
        assert_eq!(parse_year("no digits"), None);
    }
}
